### ISSUE TITLE
Redmine 2.5.x Compatibility

### ISSUE THREAD

**Issue by atopcu** [Jogi1j/redmine_closes_resolved_issues#1]
I need this plugin for redmine 2.5.2.

**Comment by Jogi1j** [comment]
Hi, I'm sorry that I did not answer immediately.
This plugin is very simple and I believe it should work on the older version Redmine, too. There are no advanced features, only redmine api and gem "rufus/scheduler".

As soon as I have time, I'll try an older version.

**Comment by atopcu** [comment]
Ok. I will try and inform you.

**Comment by atopcu** [comment]
Hi,
which issue status is "resolved", how can I set it ?

regards.

**Comment by Jogi1j** [comment]
Hi, You set the issue as resolved normally in Redmine or you can set this issues on github as resolved?

School takes my mind, probably I do not understand ;).

**Comment by atopcu** [comment]
You have defined in the code by the status ID.

https://github.com/Jogi1j/redmine_closes_resolved_issues/blob/master/app/controllers/closes_resolved_issues_controller.rb

**Comment by Jogi1j** [comment]
Hi, :status_id = 3 (is resolved) and :status_id = 5 (is closed).

Thank you for trying redmine 2.5.2.
